---
blacklist:
  - AGPL-3.0
  - GPL-2.0
  - GPL-3.0
  - CDDL-1.0

whitelist:
  - Apache-2.0
  - MIT
  - NewBSD
  - BSD-4-Clause
  - BSD-3-Clause
  - BSD-2-Clause
  - BSD-1-Clause
  - BSD-Protection
  - 0BSD
  - FreeBSD
  - LGPL-2.1
  - LGPL-3.0
  - ISC
  - MPL-2.0
  - MPL-2.0-no-copyleft-exception
  - EPL-1.0
  - Unlicense

