apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  variant: dev
configMapGenerator:
  - name: xxx-config
    namespace: xxx
    files:
    - resources/.xxx.yaml
secretGenerator:
- files:
  - xxx=secrets/xxx
  name: xxx
  namespace: xxx
resources:
- ../../base
- monitoring.yaml
