apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xxx
  namespace: xxx
spec:
  endpoints:
  - path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - xxx
  selector:
    matchLabels:
      app: xxx

