apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: XXX
  name: XXX
spec:
  replicas: 1
  selector:
    matchLabels:
      app: XXX
  template:
    metadata:
      labels:
        app: XXX
    spec:
      volumes:
      - name: config
        configMap:
          name: XXX-config
      containers:
      - name: app
        image: app-image:latest
        args:
        - -c
        - /etc/XXX/.XXX.yaml
        ports:
        - name: api
          containerPort: 8080
        - name: metrics
          containerPort: 7777
        volumeMounts:
        - name: config
          mountPath: /etc/XXX/
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 30

